# i3status-rust config file
# symlinked from ~/.config/i3status-rs/config.toml

# theme and icons settings
[theme]
theme = "solarized-dark"
[icons]
icons = "awesome5"

# display the uptime of the syste
[[block]]
block = "uptime"

# display the used disk space:
# <icon> 37GB / 906GB (896 free)
[[block]]
block = "disk_space"
interval = 20
format = " $icon $used.eng(u:B) / $total.eng(u:B) ($free.eng(u:B) free)"

# display memory and swap usage
# <icon> 56% (8.5GB/15GB) + 10% (3.2GB/32GB)
# <icon> mem: 6.7GB free + swap:  32GB free
[[block]]
block = "memory"
format = " $icon $mem_used_percents.eng(w:2,u:%) ($mem_used.eng(w:3,u:B)/$mem_total.eng(w:2,u:B)) + $swap_used_percents.eng(w:2,u:%) ($swap_used.eng(w:3,u:B)/$swap_total.eng(w:2,u:B))"
format_alt = " $icon_swap mem: $mem_avail.eng(w:3,u:B) free + swap: $swap_free.eng(w:3,u:B) free"

[[block]]
block = "cpu"
interval = 1
format = " $icon $utilization avg, $frequency.eng(w:3,u:Hz)"

# display the system load average:
# 1/5/15min avg: 0.9 0.8 0.9
[[block]]
block = "load"
interval = 1
format = " $icon 1/5/15min avg: $1m.eng(w:4) $5m.eng(w:4) $15m.eng(w:4)"

# backlight controls
#[[block]]
#block = "backlight"
#[[block]]
#block = "xrandr"
#icons = true
#resolution = true

# display the sound block
# 36%
[[block]]
block = "sound"
show_volume_when_muted = true
headphones_indicator = true

# display the cpu temp
# 28°..49°..59°
[[block]]
block = "temperature"
format = " $icon $min $average $max "
format_alt = " $icon "
idle = 25
info = 65
warning = 85

# display the battery state
[[block]]
block = "battery"
if_command = "test -e /sys/class/power_supply/BAT0"
format = " $icon $percentage $time "

# currently not working because no dbus service for bluez
#[[block]]
#block = "bluetooth"
#mac = "C8:09:A8:26:39:B8"
#hide_disconnected = true # uncomment later

# display a block about the wlan connection
[[block]]
block = "net"
device = "wlan0"
format = " $icon $ssid $signal_strength $speed_up.eng(p:K,u:B) $speed_down.eng(p:K,u:B)"
format_alt = " $icon $ipv6 $ip $frequency.eng(w:3,p:G,u:Hz)"

# display a block about the ethernet connection
[[block]]
block = "net"
device = "enp*"
format = " $icon $speed_up.eng(prefix:K) $speed_down.eng(prefix:K)"
format_alt = " $icon $ipv6 $ip"

# displays a music block
# currently not working, would require some program to attach mocp to dbus
#[[block]]
#block = "music"
#mocp --format "%state %file"

# display the current time
# Donnerstag 2022-10-06 22:51:56 (+02:00)
[[block]]
block = "time"
interval = 5
format = " $icon $timestamp.datetime(f:'%A %Y-%m-%d %H:%M:%S (%:z)', l:de_DE) "


