#!/bin/bash
#    script to update
#    Copyright (C) 2020  Johannes Schmatz <johannes_schmatz@gmx.de>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

function online_status(){
	online="no"
	[[ "$(wget http://42.org -O - -o /dev/null 2>/dev/null |head -1)" == "<HTML><HEAD>" ]]&&online="yes"
}

function wait_online(){
	onepoint="no"
	online_status
	while [[ "$online" != "yes" ]];
	do
		sleep 1
		online_status
		onepoint="yes"
		echo -n "."
	done
	if [[ $onepoint == "yes" ]]
	then
		echo
	fi
}

if [[ $1 != "--now" ]];
then
	wait_online
fi

if [[ ! -s /etc/pacman.conf ]];
then
sudo apt update && sudo apt upgrade
else
if [[ "$(grep ILoveCandy /etc/pacman.conf)" != "ILoveCandy" ]]
then
	echo 'Add the following lines to /etc/pacman.conf in section [options]'
	echo -e "\tILoveCandy"
fi

#sudo pacman -Suy
sudo pacman -Suy --ignore dhcpcd
#sudo pacman -Suy --ignore dhcpcd --ignore xf86-video-vesa

fi
# syntax
# vim: ts=8 sts=8 sw=8 noet si syntax=bash
