#!/bin/bash
#    script to update
#    Copyright (C) 2020  Johannes Schmatz <johannes_schmatz@gmx.de>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

. ~/bin/bash.rc/config.sh
. ~/bin/bash.rc/alias.sh

function verb(){
	echo -e "$C_BLUE$C_B_GREEN$@$C_NULL"
}

function run_update(){
	verb "Updating..."
	verb "$@"
	# execute the package manager
	$@

	# grab the exit status
	exit_status=$?

	if [[ $exit_status != 0 ]]; then
		echo "ERROR: exit status of '$@' is $exit_status!"
		echo "please check manually!!!"
		verb "aborting..."
		exit 1
	else
		verb "Done."
	fi
}

function detect_os(){
	if [[ ! -s /etc/pacman.conf ]]; then
		echo "raspbian"
	else
		echo "arch"
	fi
}

case "$(detect_os)" in #(((
	"arch")
		if [[ "$(grep ILoveCandy /etc/pacman.conf)" != "ILoveCandy" ]]
		then
			echo 'Add the following lines to /etc/pacman.conf ' \
				'in section [options]'
			echo -e "\tILoveCandy"
		fi

		run_update "sudo pacman -Suy"
#		run_update "sudo pacman -Suy --ignore dhcpcd"
#		run_update "sudo pacman -Suy --ignore dhcpcd --ignore xf86-video-vesa"
	;;
	"raspbian")
		run_update "sudo apt update && sudo apt upgrade"
	;;
	*)
		echo "Distro not matched!"
		echo "detect_os says: $(detect_os)"
		echo "aborting..."
	;;
esac

echo
verb "== Please restart the following processes =="
echo -e "$C_RED$C_B_BLUE"
show_update_proc
echo -e "$C_NULL"

# syntax
# vim: ts=8 sts=8 sw=8 noet si syntax=bash
