#!/bin/bash
#    script to update
#    Copyright (C) 2020  Johannes Schmatz <johannes_schmatz@gmx.de>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

function online_status(){
	online="no"
	[[ "$(wget http://42.org -O - -o /dev/null 2>/dev/null |head -1)" == "<HTML><HEAD>" ]]&&online="yes"
}

function wait_online(){
	onepoint="no"
	online_status
	while [[ "$online" != "yes" ]];
	do
		sleep 1
		online_status
		onepoint="yes"
		echo -n "."
	done
	if [[ $onepoint == "yes" ]]
	then
		echo
	fi
}

function verb(){
	echo -e "\e[34;42m$@\e[0m"
}

if [[ $1 != "--now" ]];
then
	verb "Waiting for Internet..."
	wait_online
	verb "Done."
fi

if [[ ! -s /etc/pacman.conf ]];
then
	sudo apt update && sudo apt upgrade
else
	if [[ "$(grep ILoveCandy /etc/pacman.conf)" != "ILoveCandy" ]]
	then
		echo 'Add the following lines to /etc/pacman.conf in section [options]'
		echo -e "\tILoveCandy"
	fi

	verb "Updating Package Database..."
	sudo pacman -Sy
	verb "Done."
	mkinitcpio_yes=no
	[[ "$(pacman -Qu | grep linux | wc -l)" != 0 ]]&&mkinitcpio_yes="yes"
	[[ "$(pacman -Qu | grep systemd | wc -l)" != 0 ]]&&mkinitcpio_yes="yes"
	[[ "$(pacman -Qu | grep firmware | wc -l)" != 0 ]]&&mkinitcpio_yes="yes"

	verb "Updating..."
	#sudo pacman -Suy
	sudo pacman -Suy --ignore dhcpcd
	#sudo pacman -Suy --ignore dhcpcd --ignore xf86-video-vesa
	verb "Done."

	if [[ "$mkinitcpio_yes" == "yes" ]]; then
		verb "Updating initramfs..."
		sudo mkinitcpio -p linux
		#sudo mkinitcpio -p linux-lts
		verb "Done."
	fi

fi
# syntax
# vim: ts=8 sts=8 sw=8 noet si syntax=bash
